library(MASS)
library(ggplot2)
library(dplyr)
library(tidyr)

# ==== 1. Illustrate effect of misspecification ====
mu1<-1 # True signal strength

### ==== Import data generated by Julia ====
#write.csv(results,"data/Latest_format/hd_misspec_p600_t.csv", row.names = FALSE)
plot_df<-read.csv("data/Latest_format/rawdata/hd_test/th1sensitive_p600smol.csv")
results<-read.csv("data/Latest_format/rawdata/hd_test/th1sensitive_p600e1_large.csv")
results<-read.csv("data/Latest_format/rawdata/hd_test/th1sensitive_p10e1.csv")

### ==== Generate misspecification plots ====
# For fixed n, fixed mu, vary kappa0 to see the effect of misspecification

# 1. Transform data for plotting
# This creates a 'Metric' column (Type I Error vs Power)
# and a 'Value' column (the actual rates)
plot_df_long <- results %>%
  filter(kappa0<=3) %>%
  pivot_longer(
    cols = c(error_rate, power),
    names_to = "Metric",
    values_to = "Rate"
  ) %>%
  mutate(
    Metric = ifelse(Metric == "error_rate", "Type I Error", "Power"),
    C_gamma_fact = factor(C_gamma)
  )

# 2. Create the plot
ggplot(plot_df_long, aes(x = kappa0, y = Rate, color = C_gamma_fact, linetype = Metric)) +
  geom_line(linewidth = 0.8, alpha = 0.7) +
  # Add a horizontal line for the nominal alpha/delta level
  geom_hline(yintercept = 0.9, linetype = 3, color = "blue", linewidth = 0.7) +
  geom_hline(yintercept = 0.1, linetype = 3, color = "red", linewidth = 0.7) +
  geom_vline(xintercept = mu1, color = "black", linewidth = 1.5) +
  scale_color_viridis_d(option = "turbo", end = 0.8) + # Professional color palette
  scale_linetype_manual(values = c(1, 6)) +
  labs(
    x = expression(Signal~size~input~(kappa[0])),
    y = "Empirical Probability",
    color = expression(C[gamma]),
    linetype = "Metric"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",
    text = element_text(size = 14),
    panel.grid.minor = element_blank()
  )

# Faceted plots
ggplot(plot_df_long, aes(x = kappa0, y = Rate, color = Metric)) +
  geom_line(size = 1, alpha = 0.7) +
  facet_wrap(
    ~C_gamma_fact,
    ncol = 4,
    labeller = labeller(
      C_gamma_fact = function(x) {
        paste0("C[gamma] == ", x)
      },
      .default = label_parsed
    )
  ) +
  geom_vline(xintercept = 1, color = "black", linewidth = 1)+
  geom_hline(yintercept = 0.9, linetype = 3, color = "blue", linewidth = 0.7) +
  geom_hline(yintercept = 0.1, linetype = 3, color = "red", linewidth = 0.7) +
  labs(
    x = expression(Signal~size~input~(kappa[0])),
    y = "Empirical Probability"
  )+
  theme_bw()+
  theme(
    panel.spacing = unit(1.5, "lines"),
  legend.position = "top"
  )

# === 2. Minimum signal strength vs n, p, kappa ====
# --- Plotting (Vary kappa, fix p) ---
heatmap_data<-read.csv("data/Latest_format/rawdata/hd_test/v4e1p100.csv")
heatmap_data2<-read.csv("data/Latest_format/rawdata/hd_test/v4e4p100more.csv")
heatmap_data<-rbind(heatmap_data,heatmap_data2)
#write.csv(heatmap_data,"data/Latest_format/v2e4p100.csv", row.names = FALSE)

# Heatmap for when both error guarantees are satisfied.
heatmap_data <- heatmap_data %>%
  filter(kappa>=0.15)%>%
  filter(n>=400)%>%
  filter(n<=3000)%>%
  mutate(region = case_when(
    type1_error <= 0.1  & type2_error <= 0.1  ~ "Reliably Detectable",
    type1_error > 0.1 | type2_error > 0.1  ~ "Not Reliably Detectable"
  ))

region_colors <- c(
  "Reliably Detectable" = "#3498db", # Blue
  "Not Reliably Detectable"   = "#e74c3c"  # Alizarin Red
)

boundary_data <- heatmap_data %>%
  filter(region == "Reliably Detectable") %>%
  group_by(n) %>%
  summarise(boundary_kappa0 = min(kappa), .groups = "drop") %>%
  mutate(n_inv_sqrt = n^(-0.45))

fit_boundary <- lm(boundary_kappa0 ~ 0+n_inv_sqrt, data = boundary_data)

fit_line <- data.frame(
  n = sort(unique(heatmap_data$n))
) %>%
  mutate(
    n_inv_sqrt = n^(-0.45))

fit_line$fitted_kappa0 <- predict(fit_boundary, newdata = fit_line)

ggplot(heatmap_data, aes(y = kappa, x = n, fill = region)) +
  geom_tile(color = "white", size = 0.2) +

  geom_point(
    data = boundary_data,
    aes(x = n, y = boundary_kappa0),
    inherit.aes = FALSE,
    color = "black",
    size = 1.5
  ) +

  geom_line(
    data = fit_line,
    aes(x = n, y = fitted_kappa0),
    inherit.aes = FALSE,
    color = "black",
    linewidth = 1.2
  ) +

  scale_fill_manual(values = region_colors) +
  scale_y_continuous(breaks = seq(0.15, 1.2, by = 0.05)) +
  scale_x_continuous(breaks = seq(500, 3000, by = 500)) +
  labs(
    x = "n",
    y = expression(kappa),
    fill = NULL
  ) +
  theme_minimal() +
  theme(
    legend.position = "top"
  )

# --- Plotting (Vary p, fix n) ---
heatmap_data<-read.csv("data/Latest_format/rawdata/hd_test/v4varyp_k.csv")
new_df <- expand.grid(
  kappa = seq(0.62, 0.7, by = 0.02),
  p = seq(10, 500, by = 10)
)
new_df$type1_error <- 0
new_df$type2_error <- 0
heatmap_data<-rbind(heatmap_data, new_df)

# Heatmap for when both error guarantees are satisfied
heatmap_data <- heatmap_data %>%
  # filter(p>=100) %>%
  # filter(n<=1000) %>%
  mutate(region = case_when(
    type1_error <= 0.1  & type2_error <= 0.1  ~ "Reliably Detectable",
    type1_error > 0.1 | type2_error > 0.1  ~ "Not Reliably Detectable",
    is.na(type1_error) | is.na(type2_error) ~ "Not Reliably Detectable"
  ))

region_colors <- c(
  "Reliably Detectable" = "#3498db", # Blue
  "Not Reliably Detectable"   = "#e74c3c"  # Alizarin Red
)

boundary_data <- heatmap_data %>%
  filter(region == "Reliably Detectable") %>%
  group_by(p) %>%
  summarise(boundary_kappa0 = min(kappa), .groups = "drop") %>%
  mutate(n_inv_sqrt = p^0.18)

fit_boundary <- lm(boundary_kappa0 ~ 0+n_inv_sqrt, data = boundary_data)

fit_line <- data.frame(
  p = sort(unique(heatmap_data$p))
) %>%
  mutate(
    n_inv_sqrt = p^(0.18))

fit_line$fitted_kappa0 <- predict(fit_boundary, newdata = fit_line)

ggplot(heatmap_data, aes(y = kappa, x = p, fill = region)) +
  geom_tile(color = "white", size = 0.2) +
  geom_point(
    data = boundary_data,
    aes(x = p, y = boundary_kappa0),
    inherit.aes = FALSE,
    color = "black",
    size = 1.5
  ) +
  geom_line(
    data = fit_line,
    aes(x = p, y = fitted_kappa0),
    inherit.aes = FALSE,
    color = "black",
    linewidth = 1.2
  ) +
  scale_fill_manual(values = region_colors) +
  scale_y_continuous(breaks = seq(0.15, 1.2, by = 0.05)) +
  scale_x_continuous(breaks = seq(50, 500, by = 50)) +
  labs(
    x = "p",
    y = expression(kappa),
    fill = NULL
  ) +
  theme_minimal() +
  theme(
    legend.position = "none"
  )